# Generated by Django 4.2.2 on 2023-06-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('fatherName', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=13)),
                ('studentClass', models.CharField(max_length=30)),
            ],
        ),
    ]
