# Generated by Django 4.2.2 on 2023-06-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_student_fathername_alter_student_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admNum',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
