# Generated by Django 4.2.2 on 2023-06-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_student_admnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appId', models.CharField(max_length=30, null=True)),
                ('firstName', models.CharField(max_length=30, null=True)),
                ('lastName', models.CharField(max_length=30, null=True)),
                ('fatherName', models.CharField(max_length=30, null=True)),
                ('phoneNumber', models.CharField(max_length=13, null=True)),
                ('studentClass', models.CharField(max_length=30, null=True)),
                ('isApproved', models.BooleanField(default=False)),
            ],
        ),
    ]
