# Generated by Django 4.2.2 on 2023-06-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='isApproved',
        ),
    ]
