# Generated by Django 4.2.2 on 2023-06-27 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_employee_remove_application_appid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='uid',
        ),
    ]
